### ISSUE TITLE
Verify password not working if password len !=32

### ISSUE THREAD

**Issue by nbari** [agnivade/easy-scrypt#3]
Hi, if the password length is set != 32 the verify method always fails.

**Comment by nbari** [comment]
I have my naive fix based on your implementation here: https://github.com/nbari/crypto/blob/master/scrypt/scrypt.go

**Comment by agnivade** [comment]
Ah yes ! What an embarrassing mistake .. I will fix it. Thank you for pointing it out !

**Comment by agnivade** [comment]
@nbari -  On another note, I didn't know that you were the author of immortal. Its a great tool, keep up the work !

**Comment by nbari** [comment]
many thanks :-) 👍
